Refactoring my Ruby code
robinbenitezmora/School-Library pull request #6
Opened 2022-11-14 19:47 UTC by robinbenitezmora

In this opportunity we will improve the code of our application by putting into practice OOP principles such as SOLID, KISS, YAGNI and DRY.

2022-11-14 20:44 UTC, FrederickMih requested changes
Hi @Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Screenshot from 2022-10-20 09-38-51](https://user-images.githubusercontent.com/63087491/201761479-f885e84d-e78d-4373-bd54-a7c059422e1d.png)



## Highlights :green_circle: 

- Great commit history :heavy_check_mark: 
- Correct Gitflow has been followed :heavy_check_mark: 
- PR has a title and summary :heavy_check_mark: 
- No Linter error :heavy_check_mark: 


## Required Changes ♻️
N/A
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-14 20:44 UTC, FrederickMih commented on src/main.rb
>  def main(db_data) # rubocop:todo Metrics/CyclomaticComplexity, Metrics/MethodLength
- [ ] Hi @robinbenitezmora, you'll be required to fix the Linter errors instead of disabling them. Linters flag programming/stylistic errors. We should fix these errors.

2022-11-14 20:44 UTC, FrederickMih commented on src/create_lists.rb
> +    id = gets.chomp.to_i
- [ ] Kindly make sure that the "Single Responsibility Principle" is thoroughly respected. Each class or method should have only one responsibility. All requests for input and input validation should have been done in another class/method whose responsibility is to request inputs or do validations.

2022-11-14 20:44 UTC, FrederickMih commented on src/create_methods.rb
>      end
- [ ] These pieces of code should have been placed in the main.rb file whose role is only to start the code and to ask the user for an initial choice of options(or to quit). We are working against the SRP of SOLID. The principle state that "every class, module, or function in a program should have one responsibility/purpose in a program."

2022-11-14 20:44 UTC, FrederickMih commented on src/create_methods.rb
> +    parent_permission = parent_permission == 'y'
- [ ] Kindly refer to the comment above. All requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input.

2022-11-14 20:44 UTC, FrederickMih commented on src/create_methods.rb
>      specialization = gets.chomp
- [ ] Kindly refer to the comment above.

2022-11-14 20:44 UTC, FrederickMih commented on src/create_methods.rb
> +    author = gets.chomp
- [ ] Kindly refer to the comments above.

2022-11-14 20:44 UTC, FrederickMih commented on src/create_methods.rb
>    def create_rental(db_data) # rubocop:todo Metrics/MethodLength
- [ ] Fix :wrench:  Linter errors 


- [ ] Line 73, 81, 84. Please do not request inputs from the user in this method. This should have been done somewhere else(in a class or method) whose main purpose is for that. You can equally create different files with classes/methods to carry out that specific functionality.

2022-11-15 01:36 UTC, Davidosky007 approved these changes
Hi @robinbenitezmora @asnganje 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Code refactored using YAGNI, KISS, DRY principles 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 01:42 UTC, merged